FROM node:20.11.1-bullseye-slim
RUN mkdir -p /home/app/
WORKDIR /home/app
COPY . .
RUN rm -rf node_modules || true
RUN rm -rf packages/backend || true
RUN rm -rf packages/ipfs || true
RUN rm -rf packages/frontend/.next || true
RUN npm install
RUN rm ./packages/frontend/.env || true
RUN rm ./packages/frontend/.env.* || true
RUN echo "NEXTJS_PUBLIC_IPFS_URL=http://ipfs:3002/cat/" >> ./packages/frontend/.env
RUN echo "GRAPHQL_BACKEND_URL=http://graphql_server:3000/graphql" >> ./packages/frontend/.env

# FROM node:20.11.1-bullseye-slim
# RUN mkdir -p /home/app/
# WORKDIR /home/app
# COPY --from=builder /home/app/package.json /home/app/
# COPY --from=builder /home/app/package-lock.json /home/app/
# RUN mkdir -p /home/app/packages && mkdir -p /home/app/packages/frontend/public && mkdir -p /home/app/packages/frontend/.next/static
# RUN npm install --omit=dev
# COPY --from=builder /home/app/packages/frontend/.next/standalone/packages /home/app/packages
# COPY --from=builder /home/app/packages/frontend/.next/static /home/app/packages/frontend/.next/static
# COPY --from=builder /home/app/packages/frontend/public /home/app/packages/frontend/public
# COPY --from=builder /home/app/packages/frontend/.next/standalone/node_modules /home/app/node_modules

COPY ./scripts/frontend.sh /home/app/
RUN chmod +x /home/app/frontend.sh
EXPOSE 3000

ENTRYPOINT [ "/home/app/frontend.sh" ]