FROM node:20.11.1-bullseye-slim as builder
RUN mkdir -p /home/app/
WORKDIR /home/app
COPY . .
RUN rm -rf node_modules || true
RUN find ./packages -mindepth 1 -maxdepth 1 -type d | grep -Ev './(packages/ipfs)' | xargs rm -r
RUN npm install
RUN npm run build

FROM node:20.11.1-bullseye-slim
RUN mkdir -p /home/app/
WORKDIR /home/app/
RUN mkdir -p /home/app/packages/ipfs
COPY --from=builder /home/app/packages/ipfs /home/app/packages/ipfs
COPY --from=builder /home/app/package.json /home/app/package.json
COPY --from=builder /home/app/package-lock.json /home/app/package-lock.json
RUN npm install --omit=dev
RUN npm install forever

EXPOSE 3002

ENTRYPOINT [ "npm", "run", "ipfs:prod" ]
