name: Docker build of frontend/backend/ipfs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      -
        name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockefile_frontend
          tags: localhost:5000/fullstack-challenge:frotntend
      -
        name: Build and push frontend_slim
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockefile_frontend_slim
          tags: localhost:5000/fullstack-challenge:frotntend_slim
      -
        name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockefile_backend
          tags: localhost:5000/fullstack-challenge:backend
      -
        name: Build and push ipfs
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockefile_ipfs
          tags: localhost:5000/fullstack-challenge:ipfs
      -
        name: Pull frontend image down successfully
        run: docker pull localhost:5000/fullstack-challenge:frotntend
      -
        name: Pull frontend_slim image down successfully
        run: docker pull localhost:5000/fullstack-challenge:frotntend_slim
      -
        name: Pull backend image down successfully
        run: docker pull localhost:5000/fullstack-challenge:backend
      -
        name: Pull ipfs image down successfully
        run: docker pull localhost:5000/fullstack-challenge:ipfs
